[features]
seeds = false
skip-lint = false
[programs.localnet]
myepicproject = "Blah Blah"

[registry]
url = "Blah blah"

[provider]
cluster = "Localnet"
wallet = "url location of id.json file"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
